RNG_SEED: 1000
DATASET:
  NAME: ISIC2020 
  ROOT_DIR: 'data/ISIC2020'
  VAL_RATIO: 0.1
  AUG_METHOD: 'isic'
  METRICS: ['AUC', 'F1', 'Accuracy']
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 2
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.01
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True