# EXP_NAME: 'SOME_RANDOM_NAME'
RNG_SEED: 1000
GPU_ID: '0'
DATASET:
  NAME: NCT-CRC-HE-100K 
  ROOT_DIR: 'data/NCT/NCT-CRC-HE-100K'
  METRICS: ['Accuracy']
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True