# EXP_NAME: 'SOME_RANDOM_NAME'
RNG_SEED: 1000
GPU_ID: '0'
DATASET:
  NAME: ISIC2020 
  AUG_METHOD: 'isic'
  ROOT_DIR: 'data/ISIC2020'
  METRICS: ['AUC']
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True