DATASET:
  NAME: ISIC2020
  ROOT_DIR: 'data/ISIC2020'
  VAL_RATIO: 0.1
  AUG_METHOD: 'isic'
  METRICS: ['AUC', 'Accuracy']
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 2
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.01
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 10
TEST:
  SPLIT: test
  BATCH_SIZE: 512
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L: 50.
  BUDGET_SIZE: 50
  MAX_ITER: 5
  LOAD_PREVIOUS_MODEL: False  # train form scratch for each step