DATASET:
  NAME: NCT-CRC-HE-100K 
  ROOT_DIR: 'data/NCT/NCT-CRC-HE-100K'
  VAL_RATIO: 0.1
  AUG_METHOD: 'hflip'
  METRICS: ['Accuracy']
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.01
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 512
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L: 0.01    # 0.01 * 100000 = 1000 = 100C 
  BUDGET_SIZE: 1000     # 100C
  MAX_ITER: 20
  LOAD_PREVIOUS_MODEL: False  # train form scratch for each step